<?php

namespace Database\Seeders;

use App\Models\Department;
use App\Models\Municipality;
use Illuminate\Database\Seeder;

class MunicipalitySeeder extends Seeder
{
    public function run(): void
    {
        $municipalities = [
            // Amazonas (91)
            '91' => [
                ['name' => 'Leticia', 'dian_code' => '91001'],
                ['name' => 'El Encanto', 'dian_code' => '91263'],
                ['name' => 'La Chorrera', 'dian_code' => '91405'],
                ['name' => 'La Pedrera', 'dian_code' => '91407'],
                ['name' => 'La Victoria', 'dian_code' => '91430'],
                ['name' => 'Mirití - Paraná', 'dian_code' => '91460'],
                ['name' => 'Puerto Alegría', 'dian_code' => '91530'],
                ['name' => 'Puerto Arica', 'dian_code' => '91536'],
                ['name' => 'Puerto Nariño', 'dian_code' => '91540'],
                ['name' => 'Puerto Santander', 'dian_code' => '91669'],
                ['name' => 'Tarapacá', 'dian_code' => '91798'],
            ],
            // Antioquia (05)
            '05' => [
                ['name' => 'Medellín', 'dian_code' => '05001'],
                ['name' => 'Abejorral', 'dian_code' => '05002'],
                ['name' => 'Abriaquí', 'dian_code' => '05004'],
                ['name' => 'Alejandría', 'dian_code' => '05021'],
                ['name' => 'Amagá', 'dian_code' => '05030'],
                ['name' => 'Amalfi', 'dian_code' => '05031'],
                ['name' => 'Andes', 'dian_code' => '05034'],
                ['name' => 'Angelópolis', 'dian_code' => '05036'],
                ['name' => 'Angostura', 'dian_code' => '05038'],
                ['name' => 'Anorí', 'dian_code' => '05040'],
                ['name' => 'Anzá', 'dian_code' => '05044'],
                ['name' => 'Apartadó', 'dian_code' => '05045'],
                ['name' => 'Arboletes', 'dian_code' => '05051'],
                ['name' => 'Argelia', 'dian_code' => '05055'],
                ['name' => 'Armenia', 'dian_code' => '05059'],
                ['name' => 'Barbosa', 'dian_code' => '05079'],
                ['name' => 'Bello', 'dian_code' => '05088'],
                ['name' => 'Belmira', 'dian_code' => '05086'],
                ['name' => 'Betania', 'dian_code' => '05091'],
                ['name' => 'Betulia', 'dian_code' => '05093'],
                ['name' => 'Briceño', 'dian_code' => '05107'],
                ['name' => 'Buriticá', 'dian_code' => '05113'],
                ['name' => 'Cáceres', 'dian_code' => '05120'],
                ['name' => 'Caicedo', 'dian_code' => '05125'],
                ['name' => 'Caldas', 'dian_code' => '05129'],
                ['name' => 'Campamento', 'dian_code' => '05134'],
                ['name' => 'Cañasgordas', 'dian_code' => '05138'],
                ['name' => 'Caracolí', 'dian_code' => '05142'],
                ['name' => 'Caramanta', 'dian_code' => '05145'],
                ['name' => 'Carepa', 'dian_code' => '05147'],
                ['name' => 'Carolina', 'dian_code' => '05150'],
                ['name' => 'Caucasia', 'dian_code' => '05154'],
                ['name' => 'Chigorodó', 'dian_code' => '05172'],
                ['name' => 'Cisneros', 'dian_code' => '05190'],
                ['name' => 'Cocorná', 'dian_code' => '05197'],
                ['name' => 'Concepción', 'dian_code' => '05206'],
                ['name' => 'Concordia', 'dian_code' => '05209'],
                ['name' => 'Copacabana', 'dian_code' => '05212'],
                ['name' => 'Dabeiba', 'dian_code' => '05234'],
                ['name' => 'Donmatías', 'dian_code' => '05237'],
                ['name' => 'Ebéjico', 'dian_code' => '05240'],
                ['name' => 'El Bagre', 'dian_code' => '05250'],
                ['name' => 'El Carmen de Viboral', 'dian_code' => '05148'],
                ['name' => 'El Santuario', 'dian_code' => '05697'],
                ['name' => 'Entrerríos', 'dian_code' => '05264'],
                ['name' => 'Envigado', 'dian_code' => '05266'],
                ['name' => 'Fredonia', 'dian_code' => '05282'],
                ['name' => 'Frontino', 'dian_code' => '05284'],
                ['name' => 'Giraldo', 'dian_code' => '05306'],
                ['name' => 'Girardota', 'dian_code' => '05308'],
                ['name' => 'Gómez Plata', 'dian_code' => '05310'],
                ['name' => 'Granada', 'dian_code' => '05313'],
                ['name' => 'Guadalupe', 'dian_code' => '05315'],
                ['name' => 'Guarne', 'dian_code' => '05318'],
                ['name' => 'Guatapé', 'dian_code' => '05321'],
                ['name' => 'Heliconia', 'dian_code' => '05347'],
                ['name' => 'Hispania', 'dian_code' => '05353'],
                ['name' => 'Itagüí', 'dian_code' => '05360'],
                ['name' => 'Ituango', 'dian_code' => '05361'],
                ['name' => 'Jardín', 'dian_code' => '05364'],
                ['name' => 'Jericó', 'dian_code' => '05368'],
                ['name' => 'La Ceja', 'dian_code' => '05376'],
                ['name' => 'La Estrella', 'dian_code' => '05380'],
                ['name' => 'La Pintada', 'dian_code' => '05390'],
                ['name' => 'La Unión', 'dian_code' => '05400'],
                ['name' => 'Liborina', 'dian_code' => '05411'],
                ['name' => 'Maceo', 'dian_code' => '05425'],
                ['name' => 'Marinilla', 'dian_code' => '05440'],
                ['name' => 'Montebello', 'dian_code' => '05467'],
                ['name' => 'Murindó', 'dian_code' => '05475'],
                ['name' => 'Mutatá', 'dian_code' => '05480'],
                ['name' => 'Nariño', 'dian_code' => '05483'],
                ['name' => 'Necoclí', 'dian_code' => '05490'],
                ['name' => 'Nechí', 'dian_code' => '05495'],
                ['name' => 'Olaya', 'dian_code' => '05501'],
                ['name' => 'Peñol', 'dian_code' => '05541'],
                ['name' => 'Peque', 'dian_code' => '05543'],
                ['name' => 'Pueblorrico', 'dian_code' => '05576'],
                ['name' => 'Puerto Berrío', 'dian_code' => '05579'],
                ['name' => 'Puerto Nare', 'dian_code' => '05585'],
                ['name' => 'Puerto Triunfo', 'dian_code' => '05591'],
                ['name' => 'Remedios', 'dian_code' => '05604'],
                ['name' => 'Retiro', 'dian_code' => '05607'],
                ['name' => 'Rionegro', 'dian_code' => '05615'],
                ['name' => 'Sabanalarga', 'dian_code' => '05628'],
                ['name' => 'Sabaneta', 'dian_code' => '05631'],
                ['name' => 'Salgar', 'dian_code' => '05642'],
                ['name' => 'San Andrés de Cuerquia', 'dian_code' => '05647'],
                ['name' => 'San Carlos', 'dian_code' => '05649'],
                ['name' => 'San Francisco', 'dian_code' => '05652'],
                ['name' => 'San Jerónimo', 'dian_code' => '05656'],
                ['name' => 'San José de la Montaña', 'dian_code' => '05658'],
                ['name' => 'San Juan de Urabá', 'dian_code' => '05659'],
                ['name' => 'San Luis', 'dian_code' => '05660'],
                ['name' => 'San Pedro de los Milagros', 'dian_code' => '05664'],
                ['name' => 'San Pedro de Urabá', 'dian_code' => '05665'],
                ['name' => 'San Rafael', 'dian_code' => '05667'],
                ['name' => 'San Roque', 'dian_code' => '05670'],
                ['name' => 'San Vicente Ferrer', 'dian_code' => '05674'],
                ['name' => 'Santa Bárbara', 'dian_code' => '05679'],
                ['name' => 'Santa Rosa de Osos', 'dian_code' => '05686'],
                ['name' => 'Santo Domingo', 'dian_code' => '05690'],
                ['name' => 'Segovia', 'dian_code' => '05736'],
                ['name' => 'Sonsón', 'dian_code' => '05756'],
                ['name' => 'Sopetrán', 'dian_code' => '05761'],
                ['name' => 'Támesis', 'dian_code' => '05789'],
                ['name' => 'Tarazá', 'dian_code' => '05790'],
                ['name' => 'Tarso', 'dian_code' => '05792'],
                ['name' => 'Titiribí', 'dian_code' => '05809'],
                ['name' => 'Toledo', 'dian_code' => '05819'],
                ['name' => 'Turbo', 'dian_code' => '05837'],
                ['name' => 'Uramita', 'dian_code' => '05842'],
                ['name' => 'Urrao', 'dian_code' => '05847'],
                ['name' => 'Valdivia', 'dian_code' => '05854'],
                ['name' => 'Valparaíso', 'dian_code' => '05856'],
                ['name' => 'Vegachí', 'dian_code' => '05858'],
                ['name' => 'Venecia', 'dian_code' => '05861'],
                ['name' => 'Vigía del Fuerte', 'dian_code' => '05873'],
                ['name' => 'Yalí', 'dian_code' => '05885'],
                ['name' => 'Yarumal', 'dian_code' => '05887'],
                ['name' => 'Yolombó', 'dian_code' => '05890'],
                ['name' => 'Yondó', 'dian_code' => '05893'],
                ['name' => 'Zaragoza', 'dian_code' => '05895'],
            ],
            // Arauca (81)
            '81' => [
                ['name' => 'Arauca', 'dian_code' => '81001'],
                ['name' => 'Arauquita', 'dian_code' => '81065'],
                ['name' => 'Cravo Norte', 'dian_code' => '81220'],
                ['name' => 'Fortul', 'dian_code' => '81300'],
                ['name' => 'Puerto Rondón', 'dian_code' => '81591'],
                ['name' => 'Saravena', 'dian_code' => '81736'],
                ['name' => 'Tame', 'dian_code' => '81794'],
            ],
            // Atlántico (08)
            '08' => [
                ['name' => 'Barranquilla', 'dian_code' => '08001'],
                ['name' => 'Baranoa', 'dian_code' => '08078'],
                ['name' => 'Campo de la Cruz', 'dian_code' => '08137'],
                ['name' => 'Candelaria', 'dian_code' => '08141'],
                ['name' => 'Galapa', 'dian_code' => '08296'],
                ['name' => 'Juan de Acosta', 'dian_code' => '08372'],
                ['name' => 'Luruaco', 'dian_code' => '08421'],
                ['name' => 'Malambo', 'dian_code' => '08433'],
                ['name' => 'Manatí', 'dian_code' => '08436'],
                ['name' => 'Palmar de Varela', 'dian_code' => '08520'],
                ['name' => 'Piojó', 'dian_code' => '08549'],
                ['name' => 'Polonuevo', 'dian_code' => '08558'],
                ['name' => 'Ponedera', 'dian_code' => '08560'],
                ['name' => 'Puerto Colombia', 'dian_code' => '08573'],
                ['name' => 'Repelón', 'dian_code' => '08606'],
                ['name' => 'Sabanagrande', 'dian_code' => '08634'],
                ['name' => 'Sabanalarga', 'dian_code' => '08638'],
                ['name' => 'Santa Lucía', 'dian_code' => '08675'],
                ['name' => 'Santo Tomás', 'dian_code' => '08685'],
                ['name' => 'Soledad', 'dian_code' => '08758'],
                ['name' => 'Suan', 'dian_code' => '08770'],
                ['name' => 'Tubará', 'dian_code' => '08832'],
                ['name' => 'Usiacurí', 'dian_code' => '08849'],
            ],
            // Bogotá D.C. (11)
            '11' => [
                ['name' => 'Bogotá D.C.', 'dian_code' => '11001'],
            ],

            // Bolívar (13)
            '13' => [
                ['name' => 'Cartagena de Indias', 'dian_code' => '13001'],
                ['name' => 'Achí', 'dian_code' => '13006'],
                ['name' => 'Altos del Rosario', 'dian_code' => '13030'],
                ['name' => 'Arenal', 'dian_code' => '13042'],
                ['name' => 'Arjona', 'dian_code' => '13052'],
                ['name' => 'Arroyohondo', 'dian_code' => '13062'],
                ['name' => 'Barranco de Loba', 'dian_code' => '13074'],
                ['name' => 'Calamar', 'dian_code' => '13140'],
                ['name' => 'Cantagallo', 'dian_code' => '13160'],
                ['name' => 'Cicuco', 'dian_code' => '13188'],
                ['name' => 'Clemencia', 'dian_code' => '13222'],
                ['name' => 'Córdoba', 'dian_code' => '13212'],
                ['name' => 'El Carmen de Bolívar', 'dian_code' => '13244'],
                ['name' => 'El Guamo', 'dian_code' => '13248'],
                ['name' => 'El Peñón', 'dian_code' => '13268'],
                ['name' => 'Hatillo de Loba', 'dian_code' => '13300'],
                ['name' => 'Magangué', 'dian_code' => '13430'],
                ['name' => 'Mahates', 'dian_code' => '13433'],
                ['name' => 'Margarita', 'dian_code' => '13440'],
                ['name' => 'María la Baja', 'dian_code' => '13442'],
                ['name' => 'Montecristo', 'dian_code' => '13458'],
                ['name' => 'Mompós', 'dian_code' => '13468'],
                ['name' => 'Morales', 'dian_code' => '13473'],
                ['name' => 'Norosí', 'dian_code' => '13490'],
                ['name' => 'Pinillos', 'dian_code' => '13549'],
                ['name' => 'Regidor', 'dian_code' => '13580'],
                ['name' => 'Río Viejo', 'dian_code' => '13600'],
                ['name' => 'San Cristóbal', 'dian_code' => '13620'],
                ['name' => 'San Estanislao', 'dian_code' => '13647'],
                ['name' => 'San Fernando', 'dian_code' => '13650'],
                ['name' => 'San Jacinto', 'dian_code' => '13654'],
                ['name' => 'San Jacinto del Cauca', 'dian_code' => '13655'],
                ['name' => 'San Juan Nepomuceno', 'dian_code' => '13657'],
                ['name' => 'San Martín de Loba', 'dian_code' => '13667'],
                ['name' => 'San Pablo', 'dian_code' => '13670'],
                ['name' => 'Santa Catalina', 'dian_code' => '13673'],
                ['name' => 'Santa Rosa', 'dian_code' => '13683'],
                ['name' => 'Santa Rosa del Sur', 'dian_code' => '13688'],
                ['name' => 'Simití', 'dian_code' => '13744'],
                ['name' => 'Soplaviento', 'dian_code' => '13760'],
                ['name' => 'Talaigua Nuevo', 'dian_code' => '13780'],
                ['name' => 'Tiquisio', 'dian_code' => '13810'],
                ['name' => 'Turbaco', 'dian_code' => '13836'],
                ['name' => 'Turbaná', 'dian_code' => '13838'],
                ['name' => 'Villanueva', 'dian_code' => '13873'],
                ['name' => 'Zambrano', 'dian_code' => '13894'],
            ],
            // Boyacá (15)
            '15' => [
                ['name' => 'Tunja', 'dian_code' => '15001'],
                ['name' => 'Almeida', 'dian_code' => '15022'],
                ['name' => 'Aquitania', 'dian_code' => '15047'],
                ['name' => 'Arcabuco', 'dian_code' => '15051'],
                ['name' => 'Belén', 'dian_code' => '15087'],
                ['name' => 'Berbeo', 'dian_code' => '15090'],
                ['name' => 'Betéitiva', 'dian_code' => '15092'],
                ['name' => 'Boavita', 'dian_code' => '15097'],
                ['name' => 'Boyacá', 'dian_code' => '15104'],
                ['name' => 'Briceño', 'dian_code' => '15106'],
                ['name' => 'Buenavista', 'dian_code' => '15109'],
                ['name' => 'Busbanzá', 'dian_code' => '15114'],
                ['name' => 'Caldas', 'dian_code' => '15131'],
                ['name' => 'Campohermoso', 'dian_code' => '15135'],
                ['name' => 'Cerinza', 'dian_code' => '15162'],
                ['name' => 'Chinavita', 'dian_code' => '15172'],
                ['name' => 'Chiquinquirá', 'dian_code' => '15176'],
                ['name' => 'Chiscas', 'dian_code' => '15180'],
                ['name' => 'Chita', 'dian_code' => '15183'],
                ['name' => 'Chitaraque', 'dian_code' => '15185'],
                ['name' => 'Chivatá', 'dian_code' => '15187'],
                ['name' => 'Chivor', 'dian_code' => '15236'],
                ['name' => 'Ciénega', 'dian_code' => '15189'],
                ['name' => 'Cómbita', 'dian_code' => '15204'],
                ['name' => 'Coper', 'dian_code' => '15212'],
                ['name' => 'Corrales', 'dian_code' => '15215'],
                ['name' => 'Covarachía', 'dian_code' => '15218'],
                ['name' => 'Cubará', 'dian_code' => '15223'],
                ['name' => 'Cucaita', 'dian_code' => '15224'],
                ['name' => 'Cuítiva', 'dian_code' => '15226'],
                ['name' => 'Duitama', 'dian_code' => '15238'],
                ['name' => 'El Cocuy', 'dian_code' => '15244'],
                ['name' => 'El Espino', 'dian_code' => '15248'],
                ['name' => 'Firavitoba', 'dian_code' => '15272'],
                ['name' => 'Floresta', 'dian_code' => '15276'],
                ['name' => 'Gachantivá', 'dian_code' => '15293'],
                ['name' => 'Gámeza', 'dian_code' => '15296'],
                ['name' => 'Garagoa', 'dian_code' => '15299'],
                ['name' => 'Guacamayas', 'dian_code' => '15317'],
                ['name' => 'Guateque', 'dian_code' => '15322'],
                ['name' => 'Guayatá', 'dian_code' => '15325'],
                ['name' => 'Güicán de la Sierra', 'dian_code' => '15332'],
                ['name' => 'Iza', 'dian_code' => '15362'],
                ['name' => 'Jenesano', 'dian_code' => '15367'],
                ['name' => 'Jericó', 'dian_code' => '15368'],
                ['name' => 'La Capilla', 'dian_code' => '15380'],
                ['name' => 'La Uvita', 'dian_code' => '15403'],
                ['name' => 'La Victoria', 'dian_code' => '15401'],
                ['name' => 'Labranzagrande', 'dian_code' => '15377'],
                ['name' => 'Macanal', 'dian_code' => '15425'],
                ['name' => 'Maripí', 'dian_code' => '15442'],
                ['name' => 'Miraflores', 'dian_code' => '15455'],
                ['name' => 'Mongua', 'dian_code' => '15464'],
                ['name' => 'Monguí', 'dian_code' => '15466'],
                ['name' => 'Moniquirá', 'dian_code' => '15469'],
                ['name' => 'Motavita', 'dian_code' => '15476'],
                ['name' => 'Muzo', 'dian_code' => '15480'],
                ['name' => 'Nobsa', 'dian_code' => '15491'],
                ['name' => 'Nuevo Colón', 'dian_code' => '15494'],
                ['name' => 'Oicatá', 'dian_code' => '15500'],
                ['name' => 'Otanche', 'dian_code' => '15507'],
                ['name' => 'Pachavita', 'dian_code' => '15511'],
                ['name' => 'Páez', 'dian_code' => '15514'],
                ['name' => 'Paipa', 'dian_code' => '15516'],
                ['name' => 'Pajarito', 'dian_code' => '15518'],
                ['name' => 'Panqueba', 'dian_code' => '15522'],
                ['name' => 'Pauna', 'dian_code' => '15531'],
                ['name' => 'Paya', 'dian_code' => '15533'],
                ['name' => 'Paz de Río', 'dian_code' => '15537'],
                ['name' => 'Pesca', 'dian_code' => '15542'],
                ['name' => 'Pisba', 'dian_code' => '15550'],
                ['name' => 'Puerto Boyacá', 'dian_code' => '15572'],
                ['name' => 'Quípama', 'dian_code' => '15580'],
                ['name' => 'Ramiriquí', 'dian_code' => '15599'],
                ['name' => 'Ráquira', 'dian_code' => '15600'],
                ['name' => 'Rondón', 'dian_code' => '15621'],
                ['name' => 'Saboyá', 'dian_code' => '15632'],
                ['name' => 'Sáchica', 'dian_code' => '15638'],
                ['name' => 'Samacá', 'dian_code' => '15646'],
                ['name' => 'San Eduardo', 'dian_code' => '15660'],
                ['name' => 'San José de Pare', 'dian_code' => '15664'],
                ['name' => 'San Luis de Gaceno', 'dian_code' => '15667'],
                ['name' => 'San Mateo', 'dian_code' => '15673'],
                ['name' => 'San Miguel de Sema', 'dian_code' => '15676'],
                ['name' => 'San Pablo de Borbur', 'dian_code' => '15681'],
                ['name' => 'Santa María', 'dian_code' => '15690'],
                ['name' => 'Santa Rosa de Viterbo', 'dian_code' => '15693'],
                ['name' => 'Santa Sofía', 'dian_code' => '15696'],
                ['name' => 'Santana', 'dian_code' => '15686'],
                ['name' => 'Sativanorte', 'dian_code' => '15720'],
                ['name' => 'Sativasur', 'dian_code' => '15723'],
                ['name' => 'Siachoque', 'dian_code' => '15740'],
                ['name' => 'Soatá', 'dian_code' => '15753'],
                ['name' => 'Socha', 'dian_code' => '15757'],
                ['name' => 'Socotá', 'dian_code' => '15755'],
                ['name' => 'Sogamoso', 'dian_code' => '15759'],
                ['name' => 'Somondoco', 'dian_code' => '15761'],
                ['name' => 'Sora', 'dian_code' => '15762'],
                ['name' => 'Soracá', 'dian_code' => '15764'],
                ['name' => 'Sotaquirá', 'dian_code' => '15763'],
                ['name' => 'Susacón', 'dian_code' => '15774'],
                ['name' => 'Sutamarchán', 'dian_code' => '15776'],
                ['name' => 'Sutatenza', 'dian_code' => '15778'],
                ['name' => 'Tasco', 'dian_code' => '15790'],
                ['name' => 'Tenza', 'dian_code' => '15798'],
                ['name' => 'Tibaná', 'dian_code' => '15804'],
                ['name' => 'Tibasosa', 'dian_code' => '15806'],
                ['name' => 'Tinjacá', 'dian_code' => '15808'],
                ['name' => 'Tipacoque', 'dian_code' => '15810'],
                ['name' => 'Toca', 'dian_code' => '15814'],
                ['name' => 'Togüí', 'dian_code' => '15816'],
                ['name' => 'Tópaga', 'dian_code' => '15820'],
                ['name' => 'Tota', 'dian_code' => '15822'],
                ['name' => 'Tununguá', 'dian_code' => '15832'],
                ['name' => 'Turmequé', 'dian_code' => '15835'],
                ['name' => 'Tuta', 'dian_code' => '15837'],
                ['name' => 'Tutazá', 'dian_code' => '15839'],
                ['name' => 'Úmbita', 'dian_code' => '15842'],
                ['name' => 'Ventaquemada', 'dian_code' => '15861'],
                ['name' => 'Villa de Leyva', 'dian_code' => '15407'],
                ['name' => 'Viracachá', 'dian_code' => '15879'],
                ['name' => 'Zetaquira', 'dian_code' => '15897'],
            ],

            // Caldas (17)
            '17' => [
                ['name' => 'Manizales', 'dian_code' => '17001'],
                ['name' => 'Aguadas', 'dian_code' => '17013'],
                ['name' => 'Anserma', 'dian_code' => '17042'],
                ['name' => 'Aranzazu', 'dian_code' => '17050'],
                ['name' => 'Belalcázar', 'dian_code' => '17088'],
                ['name' => 'Chinchiná', 'dian_code' => '17174'],
                ['name' => 'Filadelfia', 'dian_code' => '17272'],
                ['name' => 'La Dorada', 'dian_code' => '17380'],
                ['name' => 'La Merced', 'dian_code' => '17388'],
                ['name' => 'Manzanares', 'dian_code' => '17433'],
                ['name' => 'Marmato', 'dian_code' => '17442'],
                ['name' => 'Marquetalia', 'dian_code' => '17444'],
                ['name' => 'Marulanda', 'dian_code' => '17446'],
                ['name' => 'Neira', 'dian_code' => '17486'],
                ['name' => 'Norcasia', 'dian_code' => '17495'],
                ['name' => 'Pácora', 'dian_code' => '17513'],
                ['name' => 'Palestina', 'dian_code' => '17524'],
                ['name' => 'Pensilvania', 'dian_code' => '17541'],
                ['name' => 'Riosucio', 'dian_code' => '17614'],
                ['name' => 'Risaralda', 'dian_code' => '17616'],
                ['name' => 'Salamina', 'dian_code' => '17653'],
                ['name' => 'Samaná', 'dian_code' => '17662'],
                ['name' => 'San José', 'dian_code' => '17665'],
                ['name' => 'Supía', 'dian_code' => '17777'],
                ['name' => 'Victoria', 'dian_code' => '17867'],
                ['name' => 'Villamaría', 'dian_code' => '17873'],
                ['name' => 'Viterbo', 'dian_code' => '17877'],
            ],
            // Caquetá (18)
            '18' => [
                ['name' => 'Florencia', 'dian_code' => '18001'],
                ['name' => 'Albania', 'dian_code' => '18029'],
                ['name' => 'Belén de los Andaquíes', 'dian_code' => '18094'],
                ['name' => 'Cartagena del Chairá', 'dian_code' => '18150'],
                ['name' => 'Curillo', 'dian_code' => '18205'],
                ['name' => 'El Doncello', 'dian_code' => '18247'],
                ['name' => 'El Paujíl', 'dian_code' => '18256'],
                ['name' => 'La Montañita', 'dian_code' => '18410'],
                ['name' => 'Milán', 'dian_code' => '18460'],
                ['name' => 'Morelia', 'dian_code' => '18479'],
                ['name' => 'Puerto Rico', 'dian_code' => '18592'],
                ['name' => 'San José del Fragua', 'dian_code' => '18610'],
                ['name' => 'San Vicente del Caguán', 'dian_code' => '18753'],
                ['name' => 'Solano', 'dian_code' => '18756'],
                ['name' => 'Solita', 'dian_code' => '18785'],
                ['name' => 'Valparaíso', 'dian_code' => '18860'],
            ],
            // Casanare (85)
            '85' => [
                ['name' => 'Yopal', 'dian_code' => '85001'],
                ['name' => 'Aguazul', 'dian_code' => '85010'],
                ['name' => 'Chámeza', 'dian_code' => '85015'],
                ['name' => 'Hato Corozal', 'dian_code' => '85125'],
                ['name' => 'La Salina', 'dian_code' => '85136'],
                ['name' => 'Maní', 'dian_code' => '85139'],
                ['name' => 'Monterrey', 'dian_code' => '85162'],
                ['name' => 'Nunchía', 'dian_code' => '85225'],
                ['name' => 'Orocué', 'dian_code' => '85230'],
                ['name' => 'Paz de Ariporo', 'dian_code' => '85250'],
                ['name' => 'Pore', 'dian_code' => '85263'],
                ['name' => 'Recetor', 'dian_code' => '85279'],
                ['name' => 'Sabanalarga', 'dian_code' => '85300'],
                ['name' => 'Sácama', 'dian_code' => '85315'],
                ['name' => 'San Luis de Palenque', 'dian_code' => '85325'],
                ['name' => 'Támara', 'dian_code' => '85400'],
                ['name' => 'Tauramena', 'dian_code' => '85410'],
                ['name' => 'Trinidad', 'dian_code' => '85430'],
                ['name' => 'Villanueva', 'dian_code' => '85440'],
            ],
            // Cauca (19)
            '19' => [
                ['name' => 'Popayán', 'dian_code' => '19001'],
                ['name' => 'Almaguer', 'dian_code' => '19022'],
                ['name' => 'Argelia', 'dian_code' => '19050'],
                ['name' => 'Balboa', 'dian_code' => '19075'],
                ['name' => 'Bolívar', 'dian_code' => '19100'],
                ['name' => 'Buenos Aires', 'dian_code' => '19110'],
                ['name' => 'Cajibío', 'dian_code' => '19130'],
                ['name' => 'Caldono', 'dian_code' => '19137'],
                ['name' => 'Caloto', 'dian_code' => '19142'],
                ['name' => 'Corinto', 'dian_code' => '19212'],
                ['name' => 'El Tambo', 'dian_code' => '19256'],
                ['name' => 'Florencia', 'dian_code' => '19290'],
                ['name' => 'Guachené', 'dian_code' => '19300'],
                ['name' => 'Guapí', 'dian_code' => '19318'],
                ['name' => 'Inzá', 'dian_code' => '19355'],
                ['name' => 'Jambaló', 'dian_code' => '19364'],
                ['name' => 'La Sierra', 'dian_code' => '19392'],
                ['name' => 'La Vega', 'dian_code' => '19397'],
                ['name' => 'López de Micay', 'dian_code' => '19418'],
                ['name' => 'Mercaderes', 'dian_code' => '19450'],
                ['name' => 'Miranda', 'dian_code' => '19455'],
                ['name' => 'Morales', 'dian_code' => '19473'],
                ['name' => 'Padilla', 'dian_code' => '19513'],
                ['name' => 'Páez', 'dian_code' => '19517'],
                ['name' => 'Patía', 'dian_code' => '19532'],
                ['name' => 'Piamonte', 'dian_code' => '19533'],
                ['name' => 'Piendamó', 'dian_code' => '19548'],
                ['name' => 'Puerto Tejada', 'dian_code' => '19573'],
                ['name' => 'Puracé', 'dian_code' => '19585'],
                ['name' => 'Rosas', 'dian_code' => '19622'],
                ['name' => 'San Sebastián', 'dian_code' => '19693'],
                ['name' => 'Santa Rosa', 'dian_code' => '19701'],
                ['name' => 'Santander de Quilichao', 'dian_code' => '19698'],
                ['name' => 'Silvia', 'dian_code' => '19743'],
                ['name' => 'Sotará', 'dian_code' => '19760'],
                ['name' => 'Suárez', 'dian_code' => '19780'],
                ['name' => 'Sucre', 'dian_code' => '19785'],
                ['name' => 'Timbío', 'dian_code' => '19807'],
                ['name' => 'Timbiquí', 'dian_code' => '19809'],
                ['name' => 'Toribío', 'dian_code' => '19821'],
                ['name' => 'Totoró', 'dian_code' => '19824'],
                ['name' => 'Villa Rica', 'dian_code' => '19845'],
            ],
            // Cesar (20)
            '20' => [
                ['name' => 'Valledupar', 'dian_code' => '20001'],
                ['name' => 'Aguachica', 'dian_code' => '20011'],
                ['name' => 'Agustín Codazzi', 'dian_code' => '20013'],
                ['name' => 'Astrea', 'dian_code' => '20032'],
                ['name' => 'Becerril', 'dian_code' => '20045'],
                ['name' => 'Bosconia', 'dian_code' => '20060'],
                ['name' => 'Chimichagua', 'dian_code' => '20175'],
                ['name' => 'Chiriguaná', 'dian_code' => '20178'],
                ['name' => 'Curumaní', 'dian_code' => '20228'],
                ['name' => 'El Copey', 'dian_code' => '20238'],
                ['name' => 'El Paso', 'dian_code' => '20250'],
                ['name' => 'Gamarra', 'dian_code' => '20295'],
                ['name' => 'González', 'dian_code' => '20310'],
                ['name' => 'La Gloria', 'dian_code' => '20383'],
                ['name' => 'La Jagua de Ibirico', 'dian_code' => '20400'],
                ['name' => 'La Paz', 'dian_code' => '20621'],
                ['name' => 'Manaure Balcón del Cesar', 'dian_code' => '20443'],
                ['name' => 'Pailitas', 'dian_code' => '20517'],
                ['name' => 'Pelaya', 'dian_code' => '20550'],
                ['name' => 'Pueblo Bello', 'dian_code' => '20570'],
                ['name' => 'Río de Oro', 'dian_code' => '20614'],
                ['name' => 'San Alberto', 'dian_code' => '20710'],
                ['name' => 'San Diego', 'dian_code' => '20750'],
                ['name' => 'San Martín', 'dian_code' => '20770'],
                ['name' => 'Tamalameque', 'dian_code' => '20787'],
            ],

            // Chocó (27)
            '27' => [
                ['name' => 'Quibdó', 'dian_code' => '27001'],
                ['name' => 'Acandí', 'dian_code' => '27006'],
                ['name' => 'Alto Baudó', 'dian_code' => '27025'],
                ['name' => 'Atrato', 'dian_code' => '27050'],
                ['name' => 'Bagadó', 'dian_code' => '27073'],
                ['name' => 'Bahía Solano', 'dian_code' => '27075'],
                ['name' => 'Bajo Baudó', 'dian_code' => '27077'],
                ['name' => 'Bojayá', 'dian_code' => '27099'],
                ['name' => 'Carmen del Darién', 'dian_code' => '27150'],
                ['name' => 'Cértegui', 'dian_code' => '27160'],
                ['name' => 'Condoto', 'dian_code' => '27205'],
                ['name' => 'El Cantón del San Pablo', 'dian_code' => '27135'],
                ['name' => 'El Carmen de Atrato', 'dian_code' => '27245'],
                ['name' => 'El Litoral del San Juan', 'dian_code' => '27250'],
                ['name' => 'Istmina', 'dian_code' => '27361'],
                ['name' => 'Juradó', 'dian_code' => '27372'],
                ['name' => 'Lloró', 'dian_code' => '27413'],
                ['name' => 'Medio Atrato', 'dian_code' => '27425'],
                ['name' => 'Medio Baudó', 'dian_code' => '27430'],
                ['name' => 'Medio San Juan', 'dian_code' => '27450'],
                ['name' => 'Nóvita', 'dian_code' => '27491'],
                ['name' => 'Nuquí', 'dian_code' => '27495'],
                ['name' => 'Río Iró', 'dian_code' => '27580'],
                ['name' => 'Río Quito', 'dian_code' => '27600'],
                ['name' => 'Riosucio', 'dian_code' => '27615'],
                ['name' => 'San José del Palmar', 'dian_code' => '27660'],
                ['name' => 'Sipí', 'dian_code' => '27745'],
                ['name' => 'Tadó', 'dian_code' => '27787'],
                ['name' => 'Unguía', 'dian_code' => '27800'],
                ['name' => 'Unión Panamericana', 'dian_code' => '27810'],
            ],
            // Córdoba (23)
            '23' => [
                ['name' => 'Montería', 'dian_code' => '23001'],
                ['name' => 'Ayapel', 'dian_code' => '23068'],
                ['name' => 'Buenavista', 'dian_code' => '23079'],
                ['name' => 'Canalete', 'dian_code' => '23090'],
                ['name' => 'Cereté', 'dian_code' => '23162'],
                ['name' => 'Chimá', 'dian_code' => '23168'],
                ['name' => 'Chinú', 'dian_code' => '23182'],
                ['name' => 'Ciénaga de Oro', 'dian_code' => '23189'],
                ['name' => 'Cotorra', 'dian_code' => '23300'],
                ['name' => 'La Apartada', 'dian_code' => '23350'],
                ['name' => 'Lorica', 'dian_code' => '23417'],
                ['name' => 'Los Córdobas', 'dian_code' => '23419'],
                ['name' => 'Momil', 'dian_code' => '23464'],
                ['name' => 'Montelíbano', 'dian_code' => '23466'],
                ['name' => 'Moñitos', 'dian_code' => '23500'],
                ['name' => 'Planeta Rica', 'dian_code' => '23555'],
                ['name' => 'Pueblo Nuevo', 'dian_code' => '23570'],
                ['name' => 'Puerto Escondido', 'dian_code' => '23574'],
                ['name' => 'Puerto Libertador', 'dian_code' => '23580'],
                ['name' => 'Purísima de la Concepción', 'dian_code' => '23586'],
                ['name' => 'Sahagún', 'dian_code' => '23660'],
                ['name' => 'San Andrés de Sotavento', 'dian_code' => '23670'],
                ['name' => 'San Antero', 'dian_code' => '23672'],
                ['name' => 'San Bernardo del Viento', 'dian_code' => '23675'],
                ['name' => 'San Carlos', 'dian_code' => '23678'],
                ['name' => 'San José de Uré', 'dian_code' => '23682'],
                ['name' => 'San Pelayo', 'dian_code' => '23686'],
                ['name' => 'Tierralta', 'dian_code' => '23807'],
                ['name' => 'Tuchín', 'dian_code' => '23815'],
                ['name' => 'Valencia', 'dian_code' => '23855'],
            ],
            // Cundinamarca (25)
            '25' => [
                ['name' => 'Agua de Dios', 'dian_code' => '25001'],
                ['name' => 'Albán', 'dian_code' => '25019'],
                ['name' => 'Anapoima', 'dian_code' => '25035'],
                ['name' => 'Anolaima', 'dian_code' => '25040'],
                ['name' => 'Apulo', 'dian_code' => '25053'],
                ['name' => 'Arbeláez', 'dian_code' => '25086'],
                ['name' => 'Beltrán', 'dian_code' => '25095'],
                ['name' => 'Bituima', 'dian_code' => '25099'],
                ['name' => 'Bojacá', 'dian_code' => '25120'],
                ['name' => 'Cabrera', 'dian_code' => '25123'],
                ['name' => 'Cachipay', 'dian_code' => '25126'],
                ['name' => 'Cajicá', 'dian_code' => '25129'],
                ['name' => 'Caparrapí', 'dian_code' => '25148'],
                ['name' => 'Cáqueza', 'dian_code' => '25151'],
                ['name' => 'Carmen de Carupa', 'dian_code' => '25154'],
                ['name' => 'Chaguaní', 'dian_code' => '25168'],
                ['name' => 'Chía', 'dian_code' => '25175'],
                ['name' => 'Chipaque', 'dian_code' => '25178'],
                ['name' => 'Choachí', 'dian_code' => '25181'],
                ['name' => 'Chocontá', 'dian_code' => '25183'],
                ['name' => 'Cogua', 'dian_code' => '25200'],
                ['name' => 'Cota', 'dian_code' => '25214'],
                ['name' => 'Cucunubá', 'dian_code' => '25224'],
                ['name' => 'El Colegio', 'dian_code' => '25245'],
                ['name' => 'El Peñón', 'dian_code' => '25258'],
                ['name' => 'El Rosal', 'dian_code' => '25260'],
                ['name' => 'Facatativá', 'dian_code' => '25269'],
                ['name' => 'Fómeque', 'dian_code' => '25279'],
                ['name' => 'Fosca', 'dian_code' => '25281'],
                ['name' => 'Funza', 'dian_code' => '25286'],
                ['name' => 'Fúquene', 'dian_code' => '25288'],
                ['name' => 'Fusagasugá', 'dian_code' => '25290'],
                ['name' => 'Gachalá', 'dian_code' => '25293'],
                ['name' => 'Gachancipá', 'dian_code' => '25295'],
                ['name' => 'Gachetá', 'dian_code' => '25297'],
                ['name' => 'Gama', 'dian_code' => '25299'],
                ['name' => 'Girardot', 'dian_code' => '25307'],
                ['name' => 'Granada', 'dian_code' => '25312'],
                ['name' => 'Guachetá', 'dian_code' => '25317'],
                ['name' => 'Guaduas', 'dian_code' => '25320'],
                ['name' => 'Guasca', 'dian_code' => '25322'],
                ['name' => 'Guataquí', 'dian_code' => '25324'],
                ['name' => 'Guatavita', 'dian_code' => '25326'],
                ['name' => 'Guayabal de Síquima', 'dian_code' => '25328'],
                ['name' => 'Guayabetal', 'dian_code' => '25335'],
                ['name' => 'Gutiérrez', 'dian_code' => '25339'],
                ['name' => 'Jerusalén', 'dian_code' => '25368'],
                ['name' => 'Junín', 'dian_code' => '25372'],
                ['name' => 'La Calera', 'dian_code' => '25377'],
                ['name' => 'La Mesa', 'dian_code' => '25386'],
                ['name' => 'La Palma', 'dian_code' => '25394'],
                ['name' => 'La Peña', 'dian_code' => '25398'],
                ['name' => 'La Vega', 'dian_code' => '25402'],
                ['name' => 'Lenguazaque', 'dian_code' => '25407'],
                ['name' => 'Machetá', 'dian_code' => '25426'],
                ['name' => 'Madrid', 'dian_code' => '25430'],
                ['name' => 'Manta', 'dian_code' => '25436'],
                ['name' => 'Medina', 'dian_code' => '25438'],
                ['name' => 'Mosquera', 'dian_code' => '25473'],
                ['name' => 'Nariño', 'dian_code' => '25483'],
                ['name' => 'Nemocón', 'dian_code' => '25486'],
                ['name' => 'Nilo', 'dian_code' => '25488'],
                ['name' => 'Nimaima', 'dian_code' => '25489'],
                ['name' => 'Nocaima', 'dian_code' => '25491'],
                ['name' => 'Pacho', 'dian_code' => '25513'],
                ['name' => 'Paime', 'dian_code' => '25518'],
                ['name' => 'Pandi', 'dian_code' => '25524'],
                ['name' => 'Paratebueno', 'dian_code' => '25530'],
                ['name' => 'Pasca', 'dian_code' => '25535'],
                ['name' => 'Puerto Salgar', 'dian_code' => '25572'],
                ['name' => 'Pulí', 'dian_code' => '25580'],
                ['name' => 'Quebradanegra', 'dian_code' => '25592'],
                ['name' => 'Quetame', 'dian_code' => '25594'],
                ['name' => 'Quipile', 'dian_code' => '25596'],
                ['name' => 'Ricaurte', 'dian_code' => '25612'],
                ['name' => 'San Antonio del Tequendama', 'dian_code' => '25645'],
                ['name' => 'San Bernardo', 'dian_code' => '25649'],
                ['name' => 'San Cayetano', 'dian_code' => '25653'],
                ['name' => 'San Francisco', 'dian_code' => '25658'],
                ['name' => 'San Juan de Rioseco', 'dian_code' => '25662'],
                ['name' => 'Sasaima', 'dian_code' => '25718'],
                ['name' => 'Sesquilé', 'dian_code' => '25736'],
                ['name' => 'Sibaté', 'dian_code' => '25740'],
                ['name' => 'Silvania', 'dian_code' => '25743'],
                ['name' => 'Simijaca', 'dian_code' => '25745'],
                ['name' => 'Soacha', 'dian_code' => '25754'],
                ['name' => 'Sopó', 'dian_code' => '25758'],
                ['name' => 'Subachoque', 'dian_code' => '25769'],
                ['name' => 'Suesca', 'dian_code' => '25772'],
                ['name' => 'Supatá', 'dian_code' => '25777'],
                ['name' => 'Susa', 'dian_code' => '25779'],
                ['name' => 'Sutatausa', 'dian_code' => '25781'],
                ['name' => 'Tabio', 'dian_code' => '25785'],
                ['name' => 'Tausa', 'dian_code' => '25793'],
                ['name' => 'Tena', 'dian_code' => '25797'],
                ['name' => 'Tenjo', 'dian_code' => '25799'],
                ['name' => 'Tibacuy', 'dian_code' => '25805'],
                ['name' => 'Tibirita', 'dian_code' => '25807'],
                ['name' => 'Tocaima', 'dian_code' => '25815'],
                ['name' => 'Tocancipá', 'dian_code' => '25817'],
                ['name' => 'Topaipí', 'dian_code' => '25823'],
                ['name' => 'Ubalá', 'dian_code' => '25839'],
                ['name' => 'Ubaque', 'dian_code' => '25841'],
                ['name' => 'Une', 'dian_code' => '25845'],
                ['name' => 'Útica', 'dian_code' => '25851'],
                ['name' => 'Venecia', 'dian_code' => '25506'],
                ['name' => 'Vergara', 'dian_code' => '25862'],
                ['name' => 'Vianí', 'dian_code' => '25867'],
                ['name' => 'Villagómez', 'dian_code' => '25871'],
                ['name' => 'Villapinzón', 'dian_code' => '25873'],
                ['name' => 'Villeta', 'dian_code' => '25875'],
                ['name' => 'Viotá', 'dian_code' => '25878'],
                ['name' => 'Yacopí', 'dian_code' => '25885'],
                ['name' => 'Zipacón', 'dian_code' => '25898'],
                ['name' => 'Zipaquirá', 'dian_code' => '25899'],
            ],

            // Guainía (94)
            '94' => [
                ['name' => 'Inírida', 'dian_code' => '94001'],
                ['name' => 'Barrancominas', 'dian_code' => '94343'],
                ['name' => 'Cacahual', 'dian_code' => '94886'],
                ['name' => 'La Guadalupe', 'dian_code' => '94885'],
                ['name' => 'Mapiripana', 'dian_code' => '94663'],
                ['name' => 'Morichal', 'dian_code' => '94888'],
                ['name' => 'Pana Pana', 'dian_code' => '94887'],
                ['name' => 'Puerto Colombia', 'dian_code' => '94884'],
                ['name' => 'San Felipe', 'dian_code' => '94883'],
            ],
            // Guaviare (95)
            '95' => [
                ['name' => 'San José del Guaviare', 'dian_code' => '95001'],
                ['name' => 'Calamar', 'dian_code' => '95015'],
                ['name' => 'El Retorno', 'dian_code' => '95025'],
                ['name' => 'Miraflores', 'dian_code' => '95200'],
            ],
            // Huila (41)
            '41' => [
                ['name' => 'Neiva', 'dian_code' => '41001'],
                ['name' => 'Acevedo', 'dian_code' => '41006'],
                ['name' => 'Agrado', 'dian_code' => '41013'],
                ['name' => 'Aipe', 'dian_code' => '41016'],
                ['name' => 'Algeciras', 'dian_code' => '41020'],
                ['name' => 'Altamira', 'dian_code' => '41026'],
                ['name' => 'Baraya', 'dian_code' => '41078'],
                ['name' => 'Campoalegre', 'dian_code' => '41132'],
                ['name' => 'Colombia', 'dian_code' => '41206'],
                ['name' => 'Elías', 'dian_code' => '41244'],
                ['name' => 'Garzón', 'dian_code' => '41298'],
                ['name' => 'Gigante', 'dian_code' => '41306'],
                ['name' => 'Guadalupe', 'dian_code' => '41319'],
                ['name' => 'Hobo', 'dian_code' => '41349'],
                ['name' => 'Íquira', 'dian_code' => '41357'],
                ['name' => 'Isnos', 'dian_code' => '41359'],
                ['name' => 'La Argentina', 'dian_code' => '41378'],
                ['name' => 'La Plata', 'dian_code' => '41396'],
                ['name' => 'Nátaga', 'dian_code' => '41483'],
                ['name' => 'Oporapa', 'dian_code' => '41503'],
                ['name' => 'Paicol', 'dian_code' => '41518'],
                ['name' => 'Palermo', 'dian_code' => '41524'],
                ['name' => 'Palestina', 'dian_code' => '41530'],
                ['name' => 'Pital', 'dian_code' => '41548'],
                ['name' => 'Pitalito', 'dian_code' => '41551'],
                ['name' => 'Rivera', 'dian_code' => '41615'],
                ['name' => 'Saladoblanco', 'dian_code' => '41660'],
                ['name' => 'San Agustín', 'dian_code' => '41668'],
                ['name' => 'Santa María', 'dian_code' => '41676'],
                ['name' => 'Suaza', 'dian_code' => '41770'],
                ['name' => 'Tarqui', 'dian_code' => '41791'],
                ['name' => 'Tello', 'dian_code' => '41799'],
                ['name' => 'Teruel', 'dian_code' => '41801'],
                ['name' => 'Tesalia', 'dian_code' => '41797'],
                ['name' => 'Timaná', 'dian_code' => '41807'],
                ['name' => 'Villavieja', 'dian_code' => '41872'],
                ['name' => 'Yaguará', 'dian_code' => '41885'],
            ],
            // La Guajira (44)
            '44' => [
                ['name' => 'Riohacha', 'dian_code' => '44001'],
                ['name' => 'Albania', 'dian_code' => '44035'],
                ['name' => 'Barrancas', 'dian_code' => '44078'],
                ['name' => 'Dibulla', 'dian_code' => '44090'],
                ['name' => 'Distracción', 'dian_code' => '44098'],
                ['name' => 'El Molino', 'dian_code' => '44110'],
                ['name' => 'Fonseca', 'dian_code' => '44279'],
                ['name' => 'Hatonuevo', 'dian_code' => '44378'],
                ['name' => 'La Jagua del Pilar', 'dian_code' => '44420'],
                ['name' => 'Maicao', 'dian_code' => '44430'],
                ['name' => 'Manaure', 'dian_code' => '44560'],
                ['name' => 'San Juan del Cesar', 'dian_code' => '44650'],
                ['name' => 'Uribia', 'dian_code' => '44847'],
                ['name' => 'Urumita', 'dian_code' => '44855'],
                ['name' => 'Villanueva', 'dian_code' => '44874'],
            ],
            // Magdalena (47)
            '47' => [
                ['name' => 'Santa Marta', 'dian_code' => '47001'],
                ['name' => 'Algarrobo', 'dian_code' => '47030'],
                ['name' => 'Aracataca', 'dian_code' => '47053'],
                ['name' => 'Ariguaní', 'dian_code' => '47058'],
                ['name' => 'Cerro de San Antonio', 'dian_code' => '47161'],
                ['name' => 'Chivolo', 'dian_code' => '47170'],
                ['name' => 'Ciénaga', 'dian_code' => '47189'],
                ['name' => 'Concordia', 'dian_code' => '47205'],
                ['name' => 'El Banco', 'dian_code' => '47245'],
                ['name' => 'El Piñón', 'dian_code' => '47258'],
                ['name' => 'El Retén', 'dian_code' => '47268'],
                ['name' => 'Fundación', 'dian_code' => '47288'],
                ['name' => 'Guamal', 'dian_code' => '47318'],
                ['name' => 'Nueva Granada', 'dian_code' => '47460'],
                ['name' => 'Pedraza', 'dian_code' => '47541'],
                ['name' => 'Pijiño del Carmen', 'dian_code' => '47545'],
                ['name' => 'Pivijay', 'dian_code' => '47551'],
                ['name' => 'Plato', 'dian_code' => '47555'],
                ['name' => 'Puebloviejo', 'dian_code' => '47570'],
                ['name' => 'Remolino', 'dian_code' => '47605'],
                ['name' => 'Sabanas de San Ángel', 'dian_code' => '47660'],
                ['name' => 'Salamina', 'dian_code' => '47675'],
                ['name' => 'San Sebastián de Buenavista', 'dian_code' => '47692'],
                ['name' => 'San Zenón', 'dian_code' => '47703'],
                ['name' => 'Santa Ana', 'dian_code' => '47707'],
                ['name' => 'Santa Bárbara de Pinto', 'dian_code' => '47720'],
                ['name' => 'Sitionuevo', 'dian_code' => '47745'],
                ['name' => 'Tenerife', 'dian_code' => '47798'],
                ['name' => 'Zapayán', 'dian_code' => '47960'],
                ['name' => 'Zona Bananera', 'dian_code' => '47980'],
            ],
            // Meta (50)
            '50' => [
                ['name' => 'Villavicencio', 'dian_code' => '50001'],
                ['name' => 'Acacías', 'dian_code' => '50006'],
                ['name' => 'Barranca de Upía', 'dian_code' => '50110'],
                ['name' => 'Cabuyaro', 'dian_code' => '50124'],
                ['name' => 'Castilla la Nueva', 'dian_code' => '50150'],
                ['name' => 'Cubarral', 'dian_code' => '50223'],
                ['name' => 'Cumaral', 'dian_code' => '50226'],
                ['name' => 'El Calvario', 'dian_code' => '50245'],
                ['name' => 'El Castillo', 'dian_code' => '50251'],
                ['name' => 'El Dorado', 'dian_code' => '50270'],
                ['name' => 'Fuente de Oro', 'dian_code' => '50287'],
                ['name' => 'Granada', 'dian_code' => '50313'],
                ['name' => 'Guamal', 'dian_code' => '50318'],
                ['name' => 'La Macarena', 'dian_code' => '50350'],
                ['name' => 'La Uribe', 'dian_code' => '50370'],
                ['name' => 'Lejanías', 'dian_code' => '50400'],
                ['name' => 'Mapiripán', 'dian_code' => '50325'],
                ['name' => 'Mesetas', 'dian_code' => '50330'],
                ['name' => 'Puerto Concordia', 'dian_code' => '50450'],
                ['name' => 'Puerto Gaitán', 'dian_code' => '50568'],
                ['name' => 'Puerto Lleras', 'dian_code' => '50577'],
                ['name' => 'Puerto López', 'dian_code' => '50573'],
                ['name' => 'Puerto Rico', 'dian_code' => '50590'],
                ['name' => 'Restrepo', 'dian_code' => '50606'],
                ['name' => 'San Carlos de Guaroa', 'dian_code' => '50680'],
                ['name' => 'San Juan de Arama', 'dian_code' => '50683'],
                ['name' => 'San Juanito', 'dian_code' => '50686'],
                ['name' => 'San Martín', 'dian_code' => '50689'],
                ['name' => 'Vistahermosa', 'dian_code' => '50711'],
            ],

            // Nariño (52)
            '52' => [
                ['name' => 'Pasto', 'dian_code' => '52001'],
                ['name' => 'Albán', 'dian_code' => '52019'],
                ['name' => 'Aldana', 'dian_code' => '52022'],
                ['name' => 'Ancuyá', 'dian_code' => '52036'],
                ['name' => 'Arboleda', 'dian_code' => '52051'],
                ['name' => 'Barbacoas', 'dian_code' => '52079'],
                ['name' => 'Belén', 'dian_code' => '52083'],
                ['name' => 'Buesaco', 'dian_code' => '52110'],
                ['name' => 'Chachagüí', 'dian_code' => '52240'],
                ['name' => 'Colón', 'dian_code' => '52203'],
                ['name' => 'Consacá', 'dian_code' => '52207'],
                ['name' => 'Contadero', 'dian_code' => '52210'],
                ['name' => 'Córdoba', 'dian_code' => '52215'],
                ['name' => 'Cuaspud', 'dian_code' => '52224'],
                ['name' => 'Cumbal', 'dian_code' => '52227'],
                ['name' => 'Cumbitara', 'dian_code' => '52233'],
                ['name' => 'El Charco', 'dian_code' => '52250'],
                ['name' => 'El Peñol', 'dian_code' => '52254'],
                ['name' => 'El Rosario', 'dian_code' => '52256'],
                ['name' => 'El Tablón de Gómez', 'dian_code' => '52258'],
                ['name' => 'El Tambo', 'dian_code' => '52260'],
                ['name' => 'Francisco Pizarro', 'dian_code' => '52520'],
                ['name' => 'Funes', 'dian_code' => '52287'],
                ['name' => 'Guachucal', 'dian_code' => '52317'],
                ['name' => 'Guaitarilla', 'dian_code' => '52320'],
                ['name' => 'Gualmatán', 'dian_code' => '52323'],
                ['name' => 'Iles', 'dian_code' => '52352'],
                ['name' => 'Imués', 'dian_code' => '52354'],
                ['name' => 'Ipiales', 'dian_code' => '52356'],
                ['name' => 'La Cruz', 'dian_code' => '52378'],
                ['name' => 'La Florida', 'dian_code' => '52381'],
                ['name' => 'La Llanada', 'dian_code' => '52385'],
                ['name' => 'La Tola', 'dian_code' => '52390'],
                ['name' => 'La Unión', 'dian_code' => '52399'],
                ['name' => 'Leiva', 'dian_code' => '52405'],
                ['name' => 'Linares', 'dian_code' => '52411'],
                ['name' => 'Los Andes', 'dian_code' => '52418'],
                ['name' => 'Magüí', 'dian_code' => '52427'],
                ['name' => 'Mallama', 'dian_code' => '52435'],
                ['name' => 'Mosquera', 'dian_code' => '52473'],
                ['name' => 'Nariño', 'dian_code' => '52480'],
                ['name' => 'Olaya Herrera', 'dian_code' => '52490'],
                ['name' => 'Ospina', 'dian_code' => '52506'],
                ['name' => 'Policarpa', 'dian_code' => '52540'],
                ['name' => 'Potosí', 'dian_code' => '52560'],
                ['name' => 'Providencia', 'dian_code' => '52565'],
                ['name' => 'Puerres', 'dian_code' => '52573'],
                ['name' => 'Pupiales', 'dian_code' => '52585'],
                ['name' => 'Ricaurte', 'dian_code' => '52612'],
                ['name' => 'Roberto Payán', 'dian_code' => '52621'],
                ['name' => 'Samaniego', 'dian_code' => '52678'],
                ['name' => 'San Bernardo', 'dian_code' => '52685'],
                ['name' => 'San Lorenzo', 'dian_code' => '52687'],
                ['name' => 'San Pablo', 'dian_code' => '52693'],
                ['name' => 'San Pedro de Cartago', 'dian_code' => '52694'],
                ['name' => 'Sandoná', 'dian_code' => '52683'],
                ['name' => 'Santa Bárbara', 'dian_code' => '52696'],
                ['name' => 'Santacruz', 'dian_code' => '52699'],
                ['name' => 'Sapuyes', 'dian_code' => '52720'],
                ['name' => 'Taminango', 'dian_code' => '52786'],
                ['name' => 'Tangua', 'dian_code' => '52788'],
                ['name' => 'Tumaco', 'dian_code' => '52835'],
                ['name' => 'Túquerres', 'dian_code' => '52838'],
                ['name' => 'Yacuanquer', 'dian_code' => '52885'],
            ],
            // Norte de Santander (54)
            '54' => [
                ['name' => 'Cúcuta', 'dian_code' => '54001'],
                ['name' => 'Ábrego', 'dian_code' => '54003'],
                ['name' => 'Arboledas', 'dian_code' => '54051'],
                ['name' => 'Bochalema', 'dian_code' => '54099'],
                ['name' => 'Bucarasica', 'dian_code' => '54109'],
                ['name' => 'Cáchira', 'dian_code' => '54128'],
                ['name' => 'Cácota', 'dian_code' => '54125'],
                ['name' => 'Chinácota', 'dian_code' => '54172'],
                ['name' => 'Chitagá', 'dian_code' => '54174'],
                ['name' => 'Convención', 'dian_code' => '54206'],
                ['name' => 'Cucutilla', 'dian_code' => '54223'],
                ['name' => 'Durania', 'dian_code' => '54239'],
                ['name' => 'El Carmen', 'dian_code' => '54245'],
                ['name' => 'El Tarra', 'dian_code' => '54250'],
                ['name' => 'El Zulia', 'dian_code' => '54261'],
                ['name' => 'Gramalote', 'dian_code' => '54313'],
                ['name' => 'Hacarí', 'dian_code' => '54344'],
                ['name' => 'Herrán', 'dian_code' => '54347'],
                ['name' => 'La Esperanza', 'dian_code' => '54385'],
                ['name' => 'La Playa', 'dian_code' => '54398'],
                ['name' => 'Labateca', 'dian_code' => '54377'],
                ['name' => 'Los Patios', 'dian_code' => '54405'],
                ['name' => 'Lourdes', 'dian_code' => '54418'],
                ['name' => 'Mutiscua', 'dian_code' => '54480'],
                ['name' => 'Ocaña', 'dian_code' => '54498'],
                ['name' => 'Pamplona', 'dian_code' => '54518'],
                ['name' => 'Pamplonita', 'dian_code' => '54520'],
                ['name' => 'Puerto Santander', 'dian_code' => '54553'],
                ['name' => 'Ragonvalia', 'dian_code' => '54599'],
                ['name' => 'Salazar', 'dian_code' => '54660'],
                ['name' => 'San Calixto', 'dian_code' => '54670'],
                ['name' => 'San Cayetano', 'dian_code' => '54673'],
                ['name' => 'Santiago', 'dian_code' => '54680'],
                ['name' => 'Sardinata', 'dian_code' => '54720'],
                ['name' => 'Silos', 'dian_code' => '54743'],
                ['name' => 'Teorama', 'dian_code' => '54800'],
                ['name' => 'Tibú', 'dian_code' => '54810'],
                ['name' => 'Toledo', 'dian_code' => '54820'],
                ['name' => 'Villa Caro', 'dian_code' => '54871'],
                ['name' => 'Villa del Rosario', 'dian_code' => '54874'],
            ],
            // Putumayo (86)
            '86' => [
                ['name' => 'Mocoa', 'dian_code' => '86001'],
                ['name' => 'Colón', 'dian_code' => '86219'],
                ['name' => 'Leguízamo', 'dian_code' => '86573'],
                ['name' => 'Orito', 'dian_code' => '86320'],
                ['name' => 'Puerto Asís', 'dian_code' => '86568'],
                ['name' => 'Puerto Caicedo', 'dian_code' => '86569'],
                ['name' => 'Puerto Guzmán', 'dian_code' => '86571'],
                ['name' => 'San Francisco', 'dian_code' => '86755'],
                ['name' => 'San Miguel', 'dian_code' => '86757'],
                ['name' => 'Santiago', 'dian_code' => '86760'],
                ['name' => 'Sibundoy', 'dian_code' => '86749'],
                ['name' => 'Valle del Guamuez', 'dian_code' => '86865'],
                ['name' => 'Villagarzón', 'dian_code' => '86885'],
            ],
            // Quindío (63)
            '63' => [
                ['name' => 'Armenia', 'dian_code' => '63001'],
                ['name' => 'Buenavista', 'dian_code' => '63111'],
                ['name' => 'Calarcá', 'dian_code' => '63130'],
                ['name' => 'Circasia', 'dian_code' => '63190'],
                ['name' => 'Córdoba', 'dian_code' => '63212'],
                ['name' => 'Filandia', 'dian_code' => '63272'],
                ['name' => 'Génova', 'dian_code' => '63302'],
                ['name' => 'La Tebaida', 'dian_code' => '63401'],
                ['name' => 'Montenegro', 'dian_code' => '63470'],
                ['name' => 'Pijao', 'dian_code' => '63548'],
                ['name' => 'Quimbaya', 'dian_code' => '63594'],
                ['name' => 'Salento', 'dian_code' => '63690'],
            ],
            // Risaralda (66)
            '66' => [
                ['name' => 'Pereira', 'dian_code' => '66001'],
                ['name' => 'Apía', 'dian_code' => '66045'],
                ['name' => 'Balboa', 'dian_code' => '66075'],
                ['name' => 'Belén de Umbría', 'dian_code' => '66088'],
                ['name' => 'Dosquebradas', 'dian_code' => '66170'],
                ['name' => 'Guática', 'dian_code' => '66318'],
                ['name' => 'La Celia', 'dian_code' => '66383'],
                ['name' => 'La Virginia', 'dian_code' => '66400'],
                ['name' => 'Marsella', 'dian_code' => '66440'],
                ['name' => 'Mistrató', 'dian_code' => '66456'],
                ['name' => 'Pueblo Rico', 'dian_code' => '66572'],
                ['name' => 'Quinchía', 'dian_code' => '66594'],
                ['name' => 'Santa Rosa de Cabal', 'dian_code' => '66682'],
                ['name' => 'Santuario', 'dian_code' => '66687'],
            ],
            // San Andrés y Providencia (88)
            '88' => [
                ['name' => 'San Andrés', 'dian_code' => '88001'],
                ['name' => 'Providencia', 'dian_code' => '88564'],
            ],

            // Santander (68)
            '68' => [
                ['name' => 'Bucaramanga', 'dian_code' => '68001'],
                ['name' => 'Aguada', 'dian_code' => '68013'],
                ['name' => 'Albania', 'dian_code' => '68020'],
                ['name' => 'Aratoca', 'dian_code' => '68051'],
                ['name' => 'Barbosa', 'dian_code' => '68077'],
                ['name' => 'Barichara', 'dian_code' => '68079'],
                ['name' => 'Barrancabermeja', 'dian_code' => '68081'],
                ['name' => 'Betulia', 'dian_code' => '68092'],
                ['name' => 'Bolívar', 'dian_code' => '68101'],
                ['name' => 'Cabrera', 'dian_code' => '68121'],
                ['name' => 'California', 'dian_code' => '68132'],
                ['name' => 'Capitanejo', 'dian_code' => '68147'],
                ['name' => 'Carcasí', 'dian_code' => '68152'],
                ['name' => 'Cepitá', 'dian_code' => '68160'],
                ['name' => 'Cerrito', 'dian_code' => '68162'],
                ['name' => 'Charalá', 'dian_code' => '68167'],
                ['name' => 'Charta', 'dian_code' => '68169'],
                ['name' => 'Chima', 'dian_code' => '68176'],
                ['name' => 'Chipatá', 'dian_code' => '68179'],
                ['name' => 'Cimitarra', 'dian_code' => '68190'],
                ['name' => 'Concepción', 'dian_code' => '68207'],
                ['name' => 'Confines', 'dian_code' => '68209'],
                ['name' => 'Contratación', 'dian_code' => '68211'],
                ['name' => 'Coromoro', 'dian_code' => '68217'],
                ['name' => 'Curití', 'dian_code' => '68229'],
                ['name' => 'El Carmen de Chucurí', 'dian_code' => '68235'],
                ['name' => 'El Guacamayo', 'dian_code' => '68245'],
                ['name' => 'El Peñón', 'dian_code' => '68250'],
                ['name' => 'El Playón', 'dian_code' => '68255'],
                ['name' => 'Encino', 'dian_code' => '68264'],
                ['name' => 'Enciso', 'dian_code' => '68266'],
                ['name' => 'Florián', 'dian_code' => '68271'],
                ['name' => 'Floridablanca', 'dian_code' => '68276'],
                ['name' => 'Galán', 'dian_code' => '68296'],
                ['name' => 'Gámbita', 'dian_code' => '68298'],
                ['name' => 'Girón', 'dian_code' => '68307'],
                ['name' => 'Guaca', 'dian_code' => '68318'],
                ['name' => 'Guadalupe', 'dian_code' => '68320'],
                ['name' => 'Guapotá', 'dian_code' => '68322'],
                ['name' => 'Guavatá', 'dian_code' => '68324'],
                ['name' => 'Güepsa', 'dian_code' => '68327'],
                ['name' => 'Hato', 'dian_code' => '68344'],
                ['name' => 'Jesús María', 'dian_code' => '68368'],
                ['name' => 'Jordán', 'dian_code' => '68370'],
                ['name' => 'La Belleza', 'dian_code' => '68377'],
                ['name' => 'La Paz', 'dian_code' => '68397'],
                ['name' => 'Landázuri', 'dian_code' => '68385'],
                ['name' => 'Lebríja', 'dian_code' => '68406'],
                ['name' => 'Los Santos', 'dian_code' => '68418'],
                ['name' => 'Macaravita', 'dian_code' => '68425'],
                ['name' => 'Málaga', 'dian_code' => '68432'],
                ['name' => 'Matanza', 'dian_code' => '68444'],
                ['name' => 'Mogotes', 'dian_code' => '68464'],
                ['name' => 'Molagavita', 'dian_code' => '68468'],
                ['name' => 'Ocamonte', 'dian_code' => '68498'],
                ['name' => 'Oiba', 'dian_code' => '68500'],
                ['name' => 'Onzaga', 'dian_code' => '68502'],
                ['name' => 'Palmar', 'dian_code' => '68522'],
                ['name' => 'Palmas del Socorro', 'dian_code' => '68524'],
                ['name' => 'Páramo', 'dian_code' => '68533'],
                ['name' => 'Piedecuesta', 'dian_code' => '68547'],
                ['name' => 'Pinchote', 'dian_code' => '68549'],
                ['name' => 'Puente Nacional', 'dian_code' => '68572'],
                ['name' => 'Puerto Parra', 'dian_code' => '68573'],
                ['name' => 'Puerto Wilches', 'dian_code' => '68575'],
                ['name' => 'Rionegro', 'dian_code' => '68615'],
                ['name' => 'Sabana de Torres', 'dian_code' => '68655'],
                ['name' => 'San Andrés', 'dian_code' => '68669'],
                ['name' => 'San Benito', 'dian_code' => '68673'],
                ['name' => 'San Gil', 'dian_code' => '68679'],
                ['name' => 'San Joaquín', 'dian_code' => '68682'],
                ['name' => 'San José de Miranda', 'dian_code' => '68684'],
                ['name' => 'San Miguel', 'dian_code' => '68686'],
                ['name' => 'San Vicente de Chucurí', 'dian_code' => '68689'],
                ['name' => 'Santa Bárbara', 'dian_code' => '68705'],
                ['name' => 'Santa Helena del Opón', 'dian_code' => '68720'],
                ['name' => 'Simacota', 'dian_code' => '68745'],
                ['name' => 'Socorro', 'dian_code' => '68755'],
                ['name' => 'Suaita', 'dian_code' => '68770'],
                ['name' => 'Sucre', 'dian_code' => '68773'],
                ['name' => 'Suratá', 'dian_code' => '68780'],
                ['name' => 'Tona', 'dian_code' => '68820'],
                ['name' => 'Valle de San José', 'dian_code' => '68855'],
                ['name' => 'Vélez', 'dian_code' => '68861'],
                ['name' => 'Vetas', 'dian_code' => '68867'],
                ['name' => 'Villanueva', 'dian_code' => '68872'],
                ['name' => 'Zapatoca', 'dian_code' => '68895'],
            ],
            // Sucre (70)
            '70' => [
                ['name' => 'Sincelejo', 'dian_code' => '70001'],
                ['name' => 'Buenavista', 'dian_code' => '70110'],
                ['name' => 'Caimito', 'dian_code' => '70124'],
                ['name' => 'Chalán', 'dian_code' => '70230'],
                ['name' => 'Coloso', 'dian_code' => '70204'],
                ['name' => 'Corozal', 'dian_code' => '70215'],
                ['name' => 'Coveñas', 'dian_code' => '70221'],
                ['name' => 'El Roble', 'dian_code' => '70233'],
                ['name' => 'Galeras', 'dian_code' => '70235'],
                ['name' => 'Guaranda', 'dian_code' => '70265'],
                ['name' => 'La Unión', 'dian_code' => '70400'],
                ['name' => 'Los Palmitos', 'dian_code' => '70418'],
                ['name' => 'Majagual', 'dian_code' => '70429'],
                ['name' => 'Morroa', 'dian_code' => '70473'],
                ['name' => 'Ovejas', 'dian_code' => '70508'],
                ['name' => 'Palmito', 'dian_code' => '70523'],
                ['name' => 'Sampués', 'dian_code' => '70670'],
                ['name' => 'San Benito Abad', 'dian_code' => '70678'],
                ['name' => 'San Juan de Betulia', 'dian_code' => '70702'],
                ['name' => 'San Marcos', 'dian_code' => '70708'],
                ['name' => 'San Onofre', 'dian_code' => '70713'],
                ['name' => 'San Pedro', 'dian_code' => '70717'],
                ['name' => 'San Luis de Sincé', 'dian_code' => '70742'],
                ['name' => 'Santiago de Tolú', 'dian_code' => '70820'],
                ['name' => 'Sucre', 'dian_code' => '70771'],
                ['name' => 'Tolú Viejo', 'dian_code' => '70823'],
            ],
            // Tolima (73)
            '73' => [
                ['name' => 'Ibagué', 'dian_code' => '73001'],
                ['name' => 'Alpujarra', 'dian_code' => '73024'],
                ['name' => 'Alvarado', 'dian_code' => '73026'],
                ['name' => 'Ambalema', 'dian_code' => '73030'],
                ['name' => 'Anzoátegui', 'dian_code' => '73043'],
                ['name' => 'Armero', 'dian_code' => '73055'],
                ['name' => 'Ataco', 'dian_code' => '73067'],
                ['name' => 'Cajamarca', 'dian_code' => '73124'],
                ['name' => 'Carmen de Apicalá', 'dian_code' => '73148'],
                ['name' => 'Casabianca', 'dian_code' => '73152'],
                ['name' => 'Chaparral', 'dian_code' => '73168'],
                ['name' => 'Coello', 'dian_code' => '73200'],
                ['name' => 'Coyaima', 'dian_code' => '73217'],
                ['name' => 'Cunday', 'dian_code' => '73226'],
                ['name' => 'Dolores', 'dian_code' => '73236'],
                ['name' => 'Espinal', 'dian_code' => '73268'],
                ['name' => 'Falan', 'dian_code' => '73270'],
                ['name' => 'Flandes', 'dian_code' => '73275'],
                ['name' => 'Fresno', 'dian_code' => '73283'],
                ['name' => 'Guamo', 'dian_code' => '73319'],
                ['name' => 'Herveo', 'dian_code' => '73347'],
                ['name' => 'Honda', 'dian_code' => '73349'],
                ['name' => 'Icononzo', 'dian_code' => '73352'],
                ['name' => 'Lérida', 'dian_code' => '73408'],
                ['name' => 'Líbano', 'dian_code' => '73411'],
                ['name' => 'Mariquita', 'dian_code' => '73443'],
                ['name' => 'Melgar', 'dian_code' => '73449'],
                ['name' => 'Murillo', 'dian_code' => '73461'],
                ['name' => 'Natagaima', 'dian_code' => '73483'],
                ['name' => 'Ortega', 'dian_code' => '73504'],
                ['name' => 'Palocabildo', 'dian_code' => '73520'],
                ['name' => 'Piedras', 'dian_code' => '73547'],
                ['name' => 'Planadas', 'dian_code' => '73555'],
                ['name' => 'Prado', 'dian_code' => '73563'],
                ['name' => 'Purificación', 'dian_code' => '73585'],
                ['name' => 'Rioblanco', 'dian_code' => '73616'],
                ['name' => 'Roncesvalles', 'dian_code' => '73622'],
                ['name' => 'Rovira', 'dian_code' => '73624'],
                ['name' => 'Saldaña', 'dian_code' => '73671'],
                ['name' => 'San Antonio', 'dian_code' => '73675'],
                ['name' => 'San Luis', 'dian_code' => '73678'],
                ['name' => 'Santa Isabel', 'dian_code' => '73686'],
                ['name' => 'Suárez', 'dian_code' => '73770'],
                ['name' => 'Valle de San Juan', 'dian_code' => '73854'],
                ['name' => 'Venadillo', 'dian_code' => '73861'],
                ['name' => 'Villahermosa', 'dian_code' => '73870'],
                ['name' => 'Villarrica', 'dian_code' => '73873'],
            ],

            // Valle del Cauca (76)
            '76' => [
                ['name' => 'Cali', 'dian_code' => '76001'],
                ['name' => 'Alcalá', 'dian_code' => '76020'],
                ['name' => 'Andalucía', 'dian_code' => '76036'],
                ['name' => 'Ansermanuevo', 'dian_code' => '76041'],
                ['name' => 'Argelia', 'dian_code' => '76054'],
                ['name' => 'Bolívar', 'dian_code' => '76100'],
                ['name' => 'Buenaventura', 'dian_code' => '76109'],
                ['name' => 'Buga', 'dian_code' => '76111'],
                ['name' => 'Bugalagrande', 'dian_code' => '76113'],
                ['name' => 'Caicedonia', 'dian_code' => '76122'],
                ['name' => 'Calima', 'dian_code' => '76126'],
                ['name' => 'Candelaria', 'dian_code' => '76130'],
                ['name' => 'Cartago', 'dian_code' => '76147'],
                ['name' => 'Dagua', 'dian_code' => '76233'],
                ['name' => 'El Águila', 'dian_code' => '76243'],
                ['name' => 'El Cairo', 'dian_code' => '76246'],
                ['name' => 'El Cerrito', 'dian_code' => '76248'],
                ['name' => 'El Dovio', 'dian_code' => '76250'],
                ['name' => 'Florida', 'dian_code' => '76275'],
                ['name' => 'Ginebra', 'dian_code' => '76306'],
                ['name' => 'Guacarí', 'dian_code' => '76318'],
                ['name' => 'Jamundí', 'dian_code' => '76364'],
                ['name' => 'La Cumbre', 'dian_code' => '76377'],
                ['name' => 'La Unión', 'dian_code' => '76400'],
                ['name' => 'La Victoria', 'dian_code' => '76403'],
                ['name' => 'Obando', 'dian_code' => '76497'],
                ['name' => 'Palmira', 'dian_code' => '76520'],
                ['name' => 'Pradera', 'dian_code' => '76563'],
                ['name' => 'Restrepo', 'dian_code' => '76606'],
                ['name' => 'Riofrío', 'dian_code' => '76616'],
                ['name' => 'Roldanillo', 'dian_code' => '76622'],
                ['name' => 'San Pedro', 'dian_code' => '76670'],
                ['name' => 'Sevilla', 'dian_code' => '76736'],
                ['name' => 'Toro', 'dian_code' => '76823'],
                ['name' => 'Trujillo', 'dian_code' => '76828'],
                ['name' => 'Tuluá', 'dian_code' => '76834'],
                ['name' => 'Ulloa', 'dian_code' => '76845'],
                ['name' => 'Versalles', 'dian_code' => '76863'],
                ['name' => 'Vijes', 'dian_code' => '76869'],
                ['name' => 'Yotoco', 'dian_code' => '76890'],
                ['name' => 'Yumbo', 'dian_code' => '76892'],
                ['name' => 'Zarzal', 'dian_code' => '76895'],
            ],
            // Vaupés (97)
            '97' => [
                ['name' => 'Mitú', 'dian_code' => '97001'],
                ['name' => 'Carurú', 'dian_code' => '97161'],
                ['name' => 'Pacoa', 'dian_code' => '97511'],
                ['name' => 'Papunaua', 'dian_code' => '97777'],
                ['name' => 'Taraira', 'dian_code' => '97666'],
                ['name' => 'Yavaraté', 'dian_code' => '97889'],
            ],
            // Vichada (99)
            '99' => [
                ['name' => 'Puerto Carreño', 'dian_code' => '99001'],
                ['name' => 'Cumaribo', 'dian_code' => '99773'],
                ['name' => 'La Primavera', 'dian_code' => '99524'],
                ['name' => 'Santa Rosalía', 'dian_code' => '99624'],
            ],
        ];

        foreach ($municipalities as $deptCode => $deptMunicipalities) {
            $department = Department::where('dian_code', $deptCode)->first();
            
            if ($department) {
                foreach ($deptMunicipalities as $municipality) {
                    Municipality::create([
                        'name' => $municipality['name'],
                        'dian_code' => $municipality['dian_code'],
                        'department_id' => $department->id,
                    ]);
                }
            }
        }
    }
}
